### ISSUE TITLE
One doubt about an equation in your paper

### ISSUE THREAD

**Issue by TwiceMao** [GCChen97/ppa4p3d#1]
In the formula (2) in your paper, I think $\varphi_{0}$  is not the phase angle mentioned in the main paper, but the azimuth angle of the surface normal. And why does the second component of the surface normal vector have a negative sign in front of it?
Thank you for your answer.
![image](https://github.com/GCChen97/ppa4p3d/assets/43490149/d6e4e08b-590c-4cb4-8c8b-2207444cd8be)

**Comment by GCChen97** [comment]
Hi @TwiceMao , sorry for the late reply.
For Q1, the phase angle is equal to the azimuth angle of the surface normal, up to the pi/2 ambiguity, in the OPA model.
For Q2, the sign depends on the definition of the positive angle. In my definition, the positive angle is counter-clockwise.

**Comment by TwiceMao** [comment]
Thank you for your reply.
