### ISSUE TITLE
三维重建

### ISSUE THREAD

**Issue by Yancccccc** [GCChen97/ppa4p3d#2]
您好，可以给一份从深度图到三维重建的代码吗，同时，想请问您normal_from_depth.py中的depth map是哪个参数

**Comment by GCChen97** [comment]
您好，这个工作没有做完整的三维重建，只根据偏振角计算法线。depth map是`depths`。`depths`的深度图是用ACMH估计的。

**Comment by Yancccccc** [comment]
谢谢您


| |
晏川
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Guangcheng ***@***.***> |
| 发送日期 | 2024年2月19日 15:50 |
| 收件人 | ***@***.***> |
| 抄送人 | Chuan ***@***.***> ,
***@***.***> |
| 主题 | Re: [GCChen97/ppa4p3d] 三维重建 (Issue #2) |

您好，这个工作没有做完整的三维重建，只根据偏振角计算法线。depth map是depths。depths的深度图是用ACMH估计的。

**Comment by Yancccccc** [comment]
请问您的动态图是如何实现的
| |
晏川
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Guangcheng ***@***.***> |
| 发送日期 | 2024年2月19日 17:15 |
| 收件人 | ***@***.***> |
| 抄送人 | Chuan ***@***.***> ,
***@***.***> |
| 主题 | Re: [GCChen97/ppa4p3d] 三维重建 (Issue #2) |

Closed #2 as completed.

**Comment by GCChen97** [comment]
> 请问您的动态图是如何实现的 | | 晏川 | | ***@***.*** | ---- 回复的原邮件 ---- | 发件人 | Guangcheng ***@***.***> | | 发送日期 | 2024年2月19日 17:15 | | 收件人 | ***@***.***> | | 抄送人 | Chuan ***@***.***> , ***@***.***> | | 主题 | Re: [GCChen97/ppa4p3d] 三维重建 (Issue #2) | Closed #2 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

动态图是用另外写的GUI可视化的实时平面法线估计效果，用Flameshot截图。
